name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar --info
          echo "Gradle build completed successfully."
          echo "Listing build/libs directory:"
          ls -la ./build/libs

      - name: Verify JAR File Creation
        run: |
          if [ -f "./build/libs/csieReserve-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR file exists: ./build/libs/csieReserve-0.0.1-SNAPSHOT.jar"
          else
            echo "JAR file not found in ./build/libs! Exiting."
            exit 1
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-libs
          path: ./build/libs/

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-libs
          path: ./build/libs/

      - name: SCP docker-compose.yml and .env to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml,./.env"
          target: "~/app"

      - name: SCP JAR File to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build/libs/csieReserve-0.0.1-SNAPSHOT.jar"
          target: "~/app"

      - name: SSH and Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            mkdir -p build/libs
            mv csieReserve-0.0.1-SNAPSHOT.jar build/libs/
            docker-compose down
            docker-compose up -d --build
