name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar --info
          # 빌드 결과 확인
          ls -la ./build/libs

      - name: Verify JAR File
        run: |
          if [ -f "./build/libs/csieReserve-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR file found."
          else
            echo "JAR file not found!"
            exit 1
          fi

      - name: Upload code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"  # 현재 레포지토리의 모든 파일(빌드된 jar 포함)을 서버로 전송
          target: "~/app"

      - name: Run docker-compose on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            docker-compose build
            docker-compose up -d
