name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar --info
          echo "Gradle build completed successfully."
          echo "Listing build/libs directory:"
          ls -la ./build/libs

      - name: Verify JAR File Creation
        run: |
          if [ -f "./build/libs/csieReserve-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR file exists: ./build/libs/csieReserve-0.0.1-SNAPSHOT.jar"
          else
            echo "JAR file not found in ./build/libs! Exiting."
            exit 1
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-libs
          path: ./build/libs/

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-libs
          path: ./build/libs/

      - name: EC2에 SSH 접속 및 JAR 파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build/libs/csieReserve-0.0.1-SNAPSHOT.jar"
          target: "~/app/build/libs/"

      - name: Dockerfile 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./Dockerfile"
          target: "~/app/"

      - name: EC2 서버에서 애플리케이션 배포 및 docker-compose 실행
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/app
            echo "Stopping existing containers..."
            docker-compose down || true
            echo "Checking JAR file in build/libs directory..."
            if [ -f build/libs/csieReserve-0.0.1-SNAPSHOT.jar ]; then
              mv build/libs/csieReserve-0.0.1-SNAPSHOT.jar ./backend.jar
              echo "JAR file moved to backend.jar."
            else
              echo "JAR file not found in build/libs! Exiting."
              exit 1
            fi
            echo "Starting containers with docker-compose..."
            docker-compose up -d
